
import Navbar from "@/components/Navbar";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";
import { AuthProvider } from "@/context/authContext";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="h-screen gap-2 flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
